### ISSUE TITLE
Google 계정으로 로그인시 오류가 발생합니다.

### ISSUE THREAD

**Issue by okps123** [Cheongmin/VoiceReader#3]
@gyuhwankim  `AuthUI`를 통해 생성된 로그인창에서 구글 계정으로 로그인시 오류가 발생합니다.
````
Code: 16 Message: 16
````
위 메세지가 toast로 표시되고 오류 코드를 검색해보니 Firebase에 인증서(SHA1 of the development certificate)를 등록해야 된다고 합니다. 한번 확인 부탁드려요.

**Comment by gghcode** [comment]
다음 푸시때 반영하겠습니다.

**Comment by okps123** [comment]
Google 계정을 통해 로그인하는 방법을 삭제하였습니다.
